# Generated by Django 5.0 on 2023-12-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="updated_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
