# Generated by Django 5.0 on 2023-12-28 14:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0002_alter_company_created_at_alter_company_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="about",
            field=models.TextField(
                validators=[
                    django.core.validators.MinLengthValidator(
                        10, "About must be at least 10 characters"
                    )
                ]
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="location",
            field=models.CharField(
                max_length=50,
                validators=[
                    django.core.validators.MinLengthValidator(
                        5, "Location must be at least 5 characters"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="name",
            field=models.CharField(
                max_length=50,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(
                        5, "Name must be at least 5 characters"
                    )
                ],
            ),
        ),
    ]
