# Generated by Django 5.0 on 2023-12-29 07:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0003_alter_company_about_alter_company_location_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={"verbose_name": "Company", "verbose_name_plural": "Companies"},
        ),
        migrations.RemoveField(
            model_name="company",
            name="type",
        ),
        migrations.AddField(
            model_name="company",
            name="company_type",
            field=models.CharField(
                default="It",
                help_text="Type of the company",
                max_length=100,
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="about",
            field=models.TextField(
                validators=[
                    django.core.validators.MinLengthValidator(
                        10, "About must be at least 10 characters"
                    )
                ],
                verbose_name="About",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="active",
            field=models.BooleanField(default=True, verbose_name="Active"),
        ),
        migrations.AlterField(
            model_name="company",
            name="established",
            field=models.DateField(
                help_text="Date when the company was established",
                verbose_name="Established",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="location",
            field=models.CharField(
                max_length=100,
                validators=[
                    django.core.validators.MinLengthValidator(
                        5, "Location must be at least 5 characters"
                    )
                ],
                verbose_name="Location",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="name",
            field=models.CharField(
                max_length=100,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(
                        5, "Name must be at least 5 characters"
                    )
                ],
                verbose_name="Name",
            ),
        ),
    ]
